name: Deploy Next.js Static Site to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BUCKET_NAME: chatbot_next_cdn_bucket
  NODE_ENV: test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Needed to check for changes between commits

      - name: Check for changes in next_app directory
        id: check_changes
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Changes detected due to manual workflow dispatch"
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep "^next_app/" || echo "")
            if [ -z "$CHANGED_FILES" ]; then
              echo "No changes in next_app directory"
              echo "changes=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected in next_app directory"
              echo "changes=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Set up Node.js
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: next_app/package-lock.json

      - name: Install dependencies
        if: steps.check_changes.outputs.changes == 'true'
        working-directory: ./next_app
        run: npm ci

      - name: Build Next.js static site
        if: steps.check_changes.outputs.changes == 'true'
        working-directory: ./next_app
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
        run: npm run build

      - name: Set up Google Cloud SDK
        if: steps.check_changes.outputs.changes == 'true'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        if: steps.check_changes.outputs.changes == 'true'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to GCS bucket
        if: steps.check_changes.outputs.changes == 'true'
        working-directory: ./next_app
        run: |
          echo "Syncing /out directory to GCS bucket gs://${{ env.BUCKET_NAME }}"
          gsutil -m rsync -r -d out/ gs://${{ env.BUCKET_NAME }}/

          # Set appropriate cache control for static assets
          gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://${{ env.BUCKET_NAME }}/_next/static/**

          # Set shorter cache control for HTML files
          gsutil -m setmeta -h "Cache-Control:public, max-age=0, must-revalidate" gs://${{ env.BUCKET_NAME }}/*.html
